# Imagen base ligera
FROM python:3.12-slim

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./AgenteIA/

ENV PORT=3001
ENV PYTHONPATH=/app:/app/AgenteIA
EXPOSE 3001

CMD ["python", "-m", "app.server.server_mcp", "--http"]
