# app/domain/avion_repo.py
from typing import Protocol, List, Optional
from datetime import datetime

from app.domain.dto.avionDTO import AvionDTO
from app.persistence.entity.Avion import Avion

class AvionRepositorio(Protocol):
    def save(self, avion: Avion) -> Avion: ...

    def getAvion(self, avion_id: int) -> Optional[Avion]: ...

    def getAvionByFechaFabricacion(self, fecha_fabricacion: datetime) -> List[Avion]: ...

    def getAvionByEstado(self, estado: str) -> List[Avion]: ...

    def getAvionByAerolinea(self, aerolinea: str) -> List[Avion]: ...

    def delete(self, avion_id: int) -> Optional[Avion]: ...

    def edit(self, avion_id: int, avion_actualizado: Avion) -> Avion: ...
