FROM python:3.12-slim

# Instalar dependencias mínimas del sistema
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Definir directorio de trabajo
WORKDIR /app

# Copiar requirements desde la raíz
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./AgenteIA/

# Exponer puerto de la API
EXPOSE 5000

ENV PYTHONPATH=/app:/app/AgenteIA
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "1", "--timeout", "120", "-b", "0.0.0.0:5000", "app.api.api:app"]
